# Generated by Django 2.0.2 on 2019-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquecard',
            name='MosqueName',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='mosquecard',
            name='hadithOfTheDay',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mosquecard',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosquecard',
            name='mosqueBanner',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mosquecard',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
