# Generated by Django 2.0.2 on 2019-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mosquecards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('MosqueName', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('mosqueBanner', models.ImageField(default='', upload_to='images/')),
                ('hadithOfTheDay', models.TextField(blank=True, default='')),
                ('ispublished', models.BooleanField(default=False)),
                ('fajr', models.TimeField()),
                ('zuhr', models.TimeField()),
                ('asar', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
            ],
        ),
    ]
