# Generated by Django 2.0.2 on 2019-07-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosquecards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosquecards',
            old_name='zuhr',
            new_name='zuhar',
        ),
    ]
