# Generated by Django 2.0.2 on 2019-08-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquecards', '0002_auto_20190722_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquecards',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mosquecards',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
